config/routes.rb
Rails.application.routes.draw do
  resources :url, only: [:index, :create, :edit]
  get 'r/:short_url', to: 'url#redirect', as: "shorted_redirect"
  root to: "url#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :long_url, :short_url, presence: true
  validates :long_url, url: true
  validates_uniqueness_of :short_url, :long_url, case_sensitive: true

  before_validation :set_short_url
  after_create :fetch_title

  scope :most_views, -> { order("views DESC").limit(100) }

  def increment_view_count
    update_attributes(views: self.views + 1)
  end

  private

  def set_short_url
    return if self.short_url.present?
    short_url = generate_short_url
    while self.short_url.nil?
      if Url.where(short_url: short_url).exists?
        short_url = generate_short_url
        next
      end
      self.short_url = short_url
    end
  end

  def generate_short_url
    SecureRandom.base64(6).gsub("/","_").gsub(/=+$/,"")
  end

  def fetch_title
    TitleFetcherJob.perform_now(self) unless self.title.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/url_controller.rb
class UrlController < ApplicationController

  def index
    @most_views = Url.most_views
    @url = Url.new
    @shorted_url = params[:short_url]
  end

  def create
    @url = Url.new(permitted_parameters)
    if @url.save
      flash[:success] = "Url shorted!"
      redirect_to root_path(short_url: @url.short_url)
    else
      flash.now[:error] = "Url cannot be shorted!"
      @most_views = Url.most_views
      render :index
    end
  end

  def redirect
    url = Url.find_by(short_url: params[:short_url])
    url.increment_view_count # if user clicks back on browser it adds a new view, I should check for headers maybe.
    redirect_to url.long_url
  end

  private

  def permitted_parameters
    params[:url].permit(:long_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end
end

app/helpers/url_helper.rb
module UrlHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% unless flash.blank? %>
        <% flash.each do |type, message| %>
          <div class="alert <%= bootstrap_class_for(type) %>">
            <button class="close" data-dismiss="alert">×</button>
            <%= message %>
          </div>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/url/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Rails Shortener!</h1>
  <p class="lead">Paste your url and I will shorten it!</p>
  <hr class="my-4">

  <%= form_for(@url, url: url_index_path, class: "form-inline") do |f| %>
    <div class="form-group">
      <%= f.text_field :long_url, placeholder: "Url to be shortened..."  %>

      <% if @url.errors.any? %>
        <% @url.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>

      <%= f.submit "Short it!" %>
    </div>
  <% end %>

  <% if @shorted_url %>
    <p>Url has been shorted to: <%= link_to shorted_redirect_url(@shorted_url), shorted_redirect_url(@shorted_url) %></p>
  <% end %>
</div>

<table class="table">
  <tr>
    <th scope="col"># View count</th>
    <th scope="col">title</th>
    <th scope="col">long url</th>
    <th scope="col">short</th>
  </tr>

  <% @most_views.each do |url| %>
    <tr>
      <td scope="col"><%= url.views %></td>
      <td scope="col"><%= link_to url.title, shorted_redirect_path(url.short_url) %></td>
      <td scope="col"><%= link_to url.long_url, shorted_redirect_path(url.short_url) %></td>
      <td scope="col"><%= link_to url.short_url, shorted_redirect_path(url.short_url) %></td>
    </tr>
  <% end %>
</table>